name: alaiart
favicon: null
layout_spectrum: 0.7357385901268572
typography_spectrum: 0.4984158913139254
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.5903483971487731
  lightness: 0.09876113198697567
  saturation: 0.7129599493928254
  rhythmicContrast: 0.5455993129871786
purpose: []
