name: alaiart
favicon: null
layout_spectrum: 0.21919
typography_spectrum: 0.4984158913139254
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#bfcba6'
    - '#9a9c6d'
    - '#6b5528'
    - '#887c4e'
    - '#281600'
  brandStrength: 0.875
  lightness: 1
  saturation: 1
  rhythmicContrast: 0
purpose: []
